### ISSUE TITLE
Cellproject upgrade PHP version used

### ISSUE THREAD

**Issue by steinmb** [nt2-labo/cell_migrate_oaipmh#3]
The site use PHP 5.2.x that is now longer a maintained version and we should stop using it. Even the entire PHP 5.x branch is reaching EOL. https://secure.php.net/supported-versions.php

### PHP 7.1
The best thing would be to move to 7.1. But, before doing so, Drupal core and all 3-part modules AND libraries must be updated to latest version. Upgrade to latest minor version (generation) for those that req. that. The site then re-tested before live deploy.

### PHP 5.6
Minimum move. We should be able to move to 5.6.x, and that should be fine even with the current state of cell Drupal core and 3-part modules, though I should always be tested first in a dev. install first.

### PHP 7.2
Drupal core 7.59 and PHP 7.2.x is not 100% supported. Those issues have been addressed in Drupal 7.60 but this release have not yet been released.

## How to verify

* Test site in dev. before deploy.
* After site deploy verify that site work as expected and Migration of content from OPMI end point still work.

**Comment by steinmb** [comment]
@nt2-syl we should have Davin and the other added in here so they can post/follow/create issues.

**Comment by deheckman** [comment]
I have just joined.
